name: on_boarding
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  introduction_screen: ^3.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/surgeon-1.png
    - assets/images/surgeon-2.png
    - assets/images/surgery.png
